### ISSUE TITLE
Mightypork, Is there a reason why getStepCount() In SequalExportProject returns 7?

### ISSUE THREAD

**Issue by MCrafterzz** [MightyPork/rpw#113]
I changed it to 6 which fixed multiple errors in the development branch.

**Comment by MightyPork** [comment]
I have no idea, also we need a better comm channel than github issues

I'm on mastodon if you have an account (https://dev.glitch.social/@MightyPork). or e-mail, I guess. or gitter, but i never go there so that's not that great

note how there are almost no commits from me on development, idk what was done there.

btw, a good idea for bug-free development, make feature branches and then send a pull request. (even if you them accept it yourself). Explain what was done in the PR message. Squash commits when merging the PR. makes a much easier to read commit history

**Comment by MightyPork** [comment]
and change your editor to indent with tabs, for goodness sake

**Comment by AKTheKnight** [comment]
Pssh. Spaces master race. Also I'm around to help with fixing stuff as well :)

**Comment by MightyPork** [comment]
pfff 
even if, not when mixed with tabs tho :P

**Comment by MCrafterzz** [comment]
I do have email, twitter, reddit and gitter. Which one works the best? I will indent with tabs. It's hard to do the the problem thing now when I'm half into the current changes. I will do it when starting to work on new stuff tho

**Comment by MightyPork** [comment]
gitter, I suppose. I've installed the desktop app now. but don't expect me to do much on the project, maybe some obvious fixes. I don't know Java 8 and haven't touched minecraft for maybe a year...

**Comment by MCrafterzz** [comment]
I know, I'm into Minecraft so I can do the coding, the hard part is understanding how all the code works, that's where I sometimes need a little help.
