### ISSUE TITLE
RPW for Minecraft 1.9.x 

### ISSUE THREAD

**Issue by Zockerland99** [MightyPork/rpw#78]
Do you know when RPw will be updated so it can be used for Mc 1,9 ?

**Comment by MightyPork** [comment]
When someone sends a pull request :P
I'm really busy with other projects (as usual), or maybe it's just excuses, because I don't care about RPW that much, I'm not using it myself, so......

But it should work with 1.9, kind of. If you disable the fancy tree mode, I believe the pack structure is otherwise almost unchanged.

**Comment by Zockerland99** [comment]
Thanks

**Comment by MightyPork** [comment]
thanks for nothing, you meant :P
well I hope to get back to this project, but it may take a while
